### PR TITLE
Edge-to-edge manga details view

### PR DESCRIPTION
**Pull request by ivaniskandar**
Tablet UI and "Blue" theme are not affected. This also makes all controllers doing lift app bar on scroll by default.

[Preview](https://user-images.githubusercontent.com/12537387/127102139-f39de787-2093-4cf9-a858-3fe8d3ba68a4.png)

### CODE REVIEW

**Comment by CrepeTF** [comment]
@joseph619 after so many years, it is finally here

**Comment by joseph619** [comment]
Looks great, I wonder if it would be possible to have edge to edge for tablets as well somehow? 

@CrepeTF All thanks to pringle, what a madlad

**Comment by ivaniskandar** [comment]
> Looks great, I wonder if it would be possible to have edge to edge for tablets as well somehow?

It's possible but that will be a huge changes so I'll make the attempt on future PR.

**Comment by CrepeTF** [comment]
Could I get a picture of how it looks in dark theme

**Review by arkon — COMMENTED** [review]
Seems fairly good from testing it, but it does sometimes fail to make the status bar opaque when scrolling slowly in the manga details view, resulting in seeing the toolbar text in a weird position.

**Comment by CrepeTF** [comment]
@arkon screenshot? Thank

**Comment by ivaniskandar** [comment]
> Seems fairly good from testing it, but it does sometimes fail to make the status bar opaque when scrolling slowly in the manga details view, resulting in seeing the toolbar text in a weird position.

This elevation issue exists even without this, you can try it and see the elevation doesn't change when you scroll slowly without flinging. But well, it's fixed.

**Pull request merged**
