### PR TITLE
Add option to hide "Backup and restore" from more.

### PR DESCRIPTION
**Pull request by FourTOne5**

### CODE REVIEW

**Comment by ghostbear** [comment]
Why?

**Comment by arkon** [comment]
I'm going with no on this one. This is meant to force people to be aware of it.

**Comment by FourTOne5** [comment]
> I'm going with no on this one. This is meant to force people to be aware of it.

Even if it's not hidden by default 😐

**Comment by CrepeTF** [comment]
> > I'm going with no on this one. This is meant to force people to be aware of it.
> 
> Even if it's not hidden by default 😐

If people can accidentally turn on downloaded only, they'll find some way to fuck it up

**Pull request closed without merging**
