### PR TITLE
Tweak extension details screen

### PR DESCRIPTION
**Pull request by AntsyLich**
|            | Before | After |
| ----- | ----- | ----- |
| Banner |  |  |
| Info |  |  |
| Info (18+) |  |  |

### CODE REVIEW

**Comment by arkon** [comment]
PR description doko

**Comment by CrepeTF** [comment]
Description: it be looking lit sheeeeesh

https://cdn.discordapp.com/attachments/364330965444853761/976143039884050522/unknown.png

**Comment by AntsyLich** [comment]
> PR description doko

Info's now hd even amount of space. Warning banner is a little smaller

**Comment by CarlosEsco** [comment]
PR before and after screenshots

**Comment by AntsyLich** [comment]
Alright done

**Comment by CVIUS** [comment]
How does it look when "Incognito mode" and/or "Downloaded only" is enabled?

**Pull request merged**
