### PR TITLE
Add option to update trackers read progress on Libary update.

### PR DESCRIPTION
**Pull request by FourTOne5**
https://user-images.githubusercontent.com/59261191/126041241-217615b6-3e6a-4d6c-9323-6ad10c03fd95.mp4

### CODE REVIEW

**Comment by arkon** [comment]
Related issue: #1652 

I'm not sure what the benefit of this change would be. If it's to always see the proper data, opening the sheet already refreshes it. If it's to ensure it's up to date before updating after reading a chapter, there's no guarantee that a library update was done recently, nor that there was a change in between when it happened and you read a chapter on that particular device.

I think the more sensible method would be to refresh a particular manga's tracking right before it's updated when reading.

**Comment by FourTOne5** [comment]
> 
> I'm not sure what the benefit of this change would be. If it's to always see the proper data, opening the sheet already refreshes it. If it's to ensure it's up to date before updating after reading a chapter, there's no guarantee that a library update was done recently, nor that there was a change in between when it happened and you read a chapter on that particular device.

If you read a bunch of chapter when offline well tachi has no way to update it. It only gets updated if you read a chapter when online or you manually change it  So this will just update tracker read progress if it is less that of the read progress in libary during the global update period.

Well if there is a better suitable approach my ears are open.

**Comment by arkon** [comment]
Ah I think I misunderstood what this PR was even doing.

We should just adopt what J2K is doing with the queued job to run after going online again.

**Comment by FourTOne5** [comment]
> Ah I think I misunderstood what this PR was even doing.

No probs.

> We should just adopt what J2K is doing with the queued job to run after going online again.

Ah yes a queued job will be more suitable I'll take a look then.

**Pull request closed without merging**
