### PR TITLE
Add back missing start/end margins in manga info header

### PR DESCRIPTION
**Pull request by ghostbear**

### CODE REVIEW

**Comment by arkon** [comment]
Does this handle cases where some of the buttons are hidden (e.g. local manga)?

**Comment by ghostbear** [comment]
No

**Comment by arkon** [comment]
Oof you're right, that wasn't intentional.

**Comment by ghostbear** [comment]
I could probably change it to be in a horizontal list instead

**Comment by ghostbear** [comment]
Now it will always have an end margin

**Pull request merged**
