### PR TITLE
fallback to chrome when no default browser is found

### PR DESCRIPTION
**Pull request by CarlosEsco**
fall back to chrome no default browser is found, so verified extensions at least try chrome.

### CODE REVIEW

**Comment by arkon** [comment]
We may want to actually query for options and present a picker for Android 12+?

Was also noted that the app opening loop is happening on older versions too (at least Android 11), so we might need to handle that too (could be separately if you don't want it to be in this PR).

**Comment by CarlosEsco** [comment]
Updated to handle android 6+ https://developer.android.com/training/app-links#android-app-links

**Comment by arkon** [comment]
Closing this since we discovered on Discord that it was only an issue in Neko due to the lack of `QUERY_ALL_PACKAGES` permission.

I'll do the version check change separately.

**Comment by CarlosEsco** [comment]
I did end up switching to launching the intent with the match all

**Pull request closed without merging**
