### PR TITLE
Added percentage number in downloading

### LINKED ISSUE #8356: Percentage number for page loading
### Describe your suggested feature

add percentage number inside or below the chapter page loading circle

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by pratyaksh1610**
Added percentage number below the chapter during download.

Fixes #8356 

## Before

https://user-images.githubusercontent.com/76740999/206170015-b394add8-56a2-4a04-ac3f-d4b2072dbc53.mp4

## After 

https://user-images.githubusercontent.com/76740999/206170030-8bf4007c-16fb-4823-944c-33954fc3f744.mp4

### CODE REVIEW

**Comment by AntsyLich** [comment]
Did you even read the issue? It's asking for percentage inside reader not under download icon

**Comment by pratyaksh1610** [comment]
@AntsyLich Looks like I misunderstood the issue, can you give some clarity about the same, Thanks !

**Comment by pratyaksh1610** [comment]
And I wanted to ask does this feature seems relevant for the user.

**Comment by jferdous70** [comment]
I don't see how % of download in progress is useful or relevant information. looks like unnecessary bloat to me

**Pull request closed without merging**
