### PR TITLE
Create local source readable details.json file on chapter download

### PR DESCRIPTION
**Pull request by Shamicen**
If the option "Create details file on download" is checked, a local source readable details.json file will be created on chapter download. 

This means that if a manga gets copied from it's source folder to Tachiyomi/local all information like Title, Author, Artist, Description Genre and Status will be preserved. 

Could also be implemented without the toggle in Settings, since the details.json files are normally only a few hundred bytes in size and creating them had no noticeable impact on performance. 

This is my first ever Github commit I would be very grateful for all feedback and I apologize if my code does not meet the quality standards of Tachiyomi.

### CODE REVIEW

**Comment by mystic-man-rhino** [comment]
Why not make it standard ComicInfo.xml file.

**Comment by Shamicen** [comment]
> Why not make it standard ComicInfo.xml file.

I'm sorry but could you please tell me where the ComicInfo.xml is implemented? is it a new feature currently being worked on?
I looked at the documentation on https://tachiyomi.org/help/guides/local-manga/#editing-local-manga-details
and it only mentioned .json files. I also looked at the source code of LocalSource.kt and could only find the following function to read .json files.

    override suspend fun getMangaDetails(manga: MangaInfo): MangaInfo {
        var mangaInfo = manga

        val baseDirsFile = getBaseDirectoriesFiles(context)

        val coverFile = getCoverFile(manga.key, baseDirsFile)

        coverFile?.let {
            mangaInfo = mangaInfo.copy(cover = it.absolutePath)
        }
        val localDetails = getMangaDirsFiles(manga.key, baseDirsFile)
            .firstOrNull { it.extension.equals("json", ignoreCase = true) }
        if (localDetails != null) {
            val obj = json.decodeFromStream<JsonObject>(localDetails.inputStream())
            mangaInfo = mangaInfo.copy(
                title = obj["title"]?.jsonPrimitive?.contentOrNull ?: mangaInfo.title,
                author = obj["author"]?.jsonPrimitive?.contentOrNull ?: mangaInfo.author,
                artist = obj["artist"]?.jsonPrimitive?.contentOrNull ?: mangaInfo.artist,
                description = obj["description"]?.jsonPrimitive?.contentOrNull ?: mangaInfo.description,
                genres = obj["genre"]?.jsonArray?.map { it.jsonPrimitive.content } ?: mangaInfo.genres,
                status = obj["status"]?.jsonPrimitive?.intOrNull ?: mangaInfo.status,
            )
        }
        return mangaInfo
    }

I only found #4965 but I am not sure if this is already implemented fully since it is still marked open. If you know of any documention or source code could you tell me about it?

Thank you for your help and feedback I'm sorry if this is a dumb question like I said I am new to all of this.

**Comment by ghostbear** [comment]
> I'm sorry but could you please tell me where the ComicInfo.xml is implemented?

It's not implemented

**Comment by Shamicen** [comment]
> > I'm sorry but could you please tell me where the ComicInfo.xml is implemented?
> 
> It's not implemented

Ah OK thank you.

**Comment by mystic-man-rhino** [comment]
https://github.com/anansi-project/comicinfo

It might give you an idea

**Comment by mystic-man-rhino** [comment]
Not a mobile app but desktop app. 

https://github.com/ThePromidius/Manga-Manager

Which can create and edit comicinfo files.

**Comment by AntsyLich** [comment]
ComicInfo.xml can't be parsed by local source. Unless you add that support outputing as ComicInfo.xml will defeat the original purpose

**Comment by Shamicen** [comment]
> ComicInfo.xml can't be parsed by local source. Unless you add that support outputing as ComicInfo.xml will defeat the original purpose

Yeah that's why I said that in this point in time it would only be useful for importing Manga downloaded in Tachiyomi into a 3rd party app that uses ComicInfo.xml files.

**Comment by arkon** [comment]
I definitely have concerns around merging this first if the intention is to support the `ComicInfo.xml` standard, since this would sort of be throwaway work if moving away from our custom `details.json` format is desirable in the longterm.

Would you want to tackle trying to support reading those files first?

**Comment by jobobby04** [comment]
> I definitely have concerns around merging this first if the intention is to support the `ComicInfo.xml` standard, since this would sort of be throwaway work if moving away from our custom `details.json` format is desirable in the longterm.
> 
> Would you want to tackle trying to support reading those files first?

I have done that for something Loo was planning, feel free to take it from here
https://github.com/jobobby04/TachiyomiSY/commit/b1f243e3cc6768f3fbd8cb46fe0d005c311021ee

**Comment by arkon** [comment]
Thanks, yoinked to #7815.

**Comment by Shamicen** [comment]
> I definitely have concerns around merging this first if the intention is to support the `ComicInfo.xml` standard, since this would sort of be throwaway work if moving away from our custom `details.json` format is desirable in the long term.
> 
> Would you want to tackle trying to support reading those files first?

Since I've been asked here is my attempt at a function to make ComicInfo files readable by Tachiyomi: 
Shamicen@4a3a02d426c4b

I think a question we should ask if we want to adapt the ComicInfo format is how much we actually want to change the MangaDetails/SManga.kt to fit the in https://anansi-project.github.io/docs/category/comicinfo defined scheme.
In my opinion a lot of the elements they defined do not fit Tachiyomi or Manga in general all that well.

For one they have a lot of specific artist roles defined Penciller, Inker, Colorist, Letterer and CoverArtist. As far as I know no source actually provides this Information and the role names seem to come more from the Western comic Industry then from the Manga Industry. 
In my code Shamicen@4a3a02d426c4b I just used the first one mentioned which would usually be Penciller. I could have just used all of them and appended them together but if all the roles are filled by the same person that would have resulted in having the same Name 5 times. 

All of the elements in the scheme are labeled minOccurs="0"  so I would propose to simply ignore the Information that doesn't fit well or does not serve any purpose in Tachiyomi and just use the elements that Tachiyomi uses right now and add a few that seem useful from https://anansi-project.github.io/docs/comicinfo/documentation to SManga.kt (Volume for example could be nice to have).

This would make Tachiyomi and applications using the ComicInfo.xml scheme compatible with each other without requiring to many changes in  SManga.kt. 

I would also propose to add one Tachiyomi exclusive element StatusTachiyomi because neither in the 2.0 or the 2.1 draft version of the ComicInfo.xml scheme is there any mention of an element tracking the comics Publishing status. If the official scheme adds a Status one day we could switch over to it then. 

I decided against doing anything with the Tags element at this point in time because it only exists in 2.1 which is still labeled draft and I couldn't find a single sample file using it yet. 

If you guys are OK with this my next step would be to try writing a function that outputs the elements 
- Title
- Writer (author in Tachiyomi)
- Penciller (artist in Tachiyomi)
- Summary (description in Tachiyomi
- Genre
- StatusTachiyomi

following the ComicInfo.xml scheme. 

I would then make one big Pull request containing the read function, the json output from this Pull request and the xml output and implement an option to switch between them. 


Please everyone tell me what you think of my proposal and the code in Shamicen@4a3a02d426c4b.

**Comment by arkon** [comment]
So a few things to note here:

- It'd make more sense to support a more standardized format if we want to start auto-generating files (pending #7815)
- It'd probably make sense to only generate them on-demand, i.e. via a "move to local" sort of feature (#2289) _or_ if it's to be used as the data storage for in-app manga detail edits

That said, I'll mark this PR as a draft since neither of those things are quite ready yet.

**Comment by Shamicen** [comment]
Superseded by #8033

**Pull request closed without merging**
