### PR TITLE
[WIP] Convert lossless images on download

### PR DESCRIPTION
**Pull request by msm595**
This PR implements image conversion for downloaded lossless images (PNG) to save disk space. Currently these images can be converted to lossless WebP, lossy WebP, and JPG images. It is still a WIP, but I am looking for preliminary feedback on the idea in general.

### Testing
 1. Enable conversion by setting `Settings > Downloads > Convert lossless images` to either `Lossy WebP`, `Lossless WebP`, or `JPG`.
2. Change the image decoder to support WebP 1.0.0 by changing `Settings > Reader > Image Decoder` to something other than `Image`.
3. Download manga containing PNGs

### TODO
- Move conversion to separate computation scheduler, perform async / simultaneously with download
- Add some sort of UI to demonstrate conversion is taking place
- ~Add conversion to JPG for what will likely be the fastest, medium size, but worst quality option (using either bitmap.compress~ or libjpeg-turbo)
- Allow the user to specify quality / level, though this may just complicate things from a user perspective
- Split off image encoder to a separate library (I may save this till the end of the PR)
- Move image decoding into native code (remove usage of BitmapFactory.decodeFile)
- Add support for per-scanline encoding of JPEGs (and investigate if WebP can be used similarly)
 - Add support for per-scanline decoding of PNGs and BMP (to have data to take advantage of per-scanline encoding)

### Performance
Performance was measured on a Samsung S6, CPU: Samsung Exynos 7 Octa 7420 (ARMv8a). `encode` is the measure of time spent in native code converting the image, `decodeFile` is the amount of time spent decoding the png file to a bitmap (should be consistent across options). `networkFetch` is the highly variable time spent downloading files, and is only included to give a sense of time-scale.

#### Bakemonogatari - MangaDex EN - Ch 1 - 11: 348 pngs
```
no encoding / purely download: 264MB / 269,876 KB
    Total download took 1:34.450 (94,450,620,877 ns)
        networkFetch took 1:34.450 (94,450,620,877 ns)
        
lossless webp (level: 2):  164MB / 168,420 KB
    Total download took 6:22.831 (382,831,388,808 ns)
        networkFetch took 0:48.772 (48,772,694,353 ns)
        decodeFile took 0:17.645 (17,645,892,586 ns)
        encode took 5:15.073 (315,073,945,869 ns)

jpeg (quality: 90): 122 MB / 124,748 KB
    Total download took 6:35.608 (395,608,739,187 ns)
        networkFetch took 5:33.300 (333,300,234,784 ns)
        decodeFile took 0:18.899 (18,899,810,392 ns)
        encode took 0:42.127 (42,127,317,638 ns)

lossy webp (method: 4, quality: 90): 90MB / 92,068 KB
    Total download took 9:49.724 (589,724,662,113 ns)
        networkFetch took 5:43.680 (343,680,778,120 ns)
        decodeFile took 0:18.914 (18,914,821,723 ns)
        encode took 3:45.689 (225,689,611,186 ns)
```

#### A Story About Treating a Female Knight, Who Has Never Been Treated as a Woman, as a Woman - MangaDex EN - Ch 1 - 15: 109 pngs / 4 jpg 
```
no encoding / purely download: 135 MB / 138,100 KB
    Total download took 2:21.808 (141,808,719,651 ns)
        networkFetch took 2:21.808 (141,808,719,651 ns)
        
lossless webp (level: 2): 75 MB / 76,832 KB
    Total download took 1:22.291 (82,291,610,371 ns)
        networkFetch took 0:25.824 (25,824,026,886 ns)
        decodeFile took 0:08.206 (8,206,622,132 ns)
        encode took 0:47.826 (47,826,675,771 ns)

jpg (quality: 90): 61 MB / 62,256 KB
    Total download took 1:19.652 (79,652,391,123 ns)
        networkFetch took 0:53.597 (53,597,012,609 ns)
        decodeFile took 0:08.602 (8,602,771,618 ns)
        encode took 0:17.020 (17,020,906,217 ns)

lossy webp (method: 4, quality: 90): 50 MB / 50,932 KB
    Total download took 2:01.593 (121,593,689,893 ns)
        networkFetch took 0:23.497 (23,497,979,472 ns)
        decodeFile took 0:08.216 (8,216,367,796 ns)
        encode took 1:29.419 (89,419,385,168 ns)
```

#### Kumo Desu ga, Nani ka? - MangaDex EN - Ch 0 - 28.2: 708 pngs / 129 jpg
```
no encoding / purely download:  2.1 GB / 2,298,348 KB
    Total download took 15:22.051 (922,051,045,767 ns)
        networkFetch took 15:21.962 (921,962,802,394 ns)
        
lossless webp (level: 2): 1.0 GB / 1,090,144 KB
    Total download took 19:26.061 (1,166,061,460,766 ns)
        networkFetch took 6:31.277 (391,277,155,602 ns)
        decodeFile took 1:50.972 (110,972,998,758 ns)
        encode took 11:00.152 (660,152,656,156 ns)

jpg (quality: 90): 636 MB / 650,840 KB
    Total download took 22:30.488 (1,350,488,121,515 ns)
        networkFetch took 17:44.774 (1,064,774,269,752 ns)
        decodeFile took 1:52.678 (112,678,854,875 ns)
        encode took 2:50.317 (170,317,844,203 ns)

lossy webp (method: 4, quality: 90): 686 MB / 702,804 KB
    Total download took 28:04.098 (1,684,098,716,428 ns)
        networkFetch took 6:57.981 (417,981,378,575 ns)
        decodeFile took 1:56.623 (116,623,946,390 ns)
        encode took 19:06.095 (1,146,095,713,009 ns)
```

### CODE REVIEW

**Comment by inorichi** [comment]
It's not really a bad idea but I see a few problems:

1. libwebp is part of the tachiyomi build process. I don't want to add a direct dependency to the NDK when building tachiyomi, even worse with git submodules. It'd have to be moved to a separate library and compiled through JitPack for example.

Also, I don't know if webp would actually improve file sizes that much for (mostly) white and black images. Is the lossless compression the reasoning behind this choice? Another issue is that the default image decoder doesn't support webp yet, although I implemented webp decoding a few months ago but they're not included here yet.

2. `BitmapFactory.decodeFile` will crash the app. It decodes the entire bitmap into memory without any sampling and will definitely produce crashes every time a large image is downloaded (and crash again when the application is restarted and the downloader resumed). I can only see 2 solutions: either this feature is limited to Oreo users, because the `Bitmap` class doesn't have a copy of the array of pixels on API >= 26, or you pass the input stream to native code and decode the bitmap there.

**Comment by msm595** [comment]
1. Perfectly reasonable, and I will refactor to a separate repo and integrate with JitPack eventually. I just wanted to get a general sense for how it would all fit together first.

I think the file sizes speak for themselves (see Performance), where "Kumo Desu ga, Nani ka?" was shrunk from 2.1 GB to 1.0 GB for lossless WebP, 686 MB for lossy WebP, and 636 MB for JPE. Lossless compression was my reasoning to select WebP (also for generally smaller lossy files than JPG), but I have also included JPG compression.

The default image decoder doesn't support it currently, but others do which seem to work fine.

2. Image decoding in native code is pretty understandable, once again I just wanted a "rough draft" of this feature first. What is the largest file you think there will be? If it's large enough to crash the app due to memory allocation, I'm not sure it could even be converted (without downsizing first).

**Comment by inorichi** [comment]
Ah, I missed that JPG is also an option, cool then.

About image sizes, I've seen webtoons using very large dimensions, around 2000x16000. If an image like this is decoded with ARGB_8888, it'd need an allocation of 122MB, and even if there are 122MB available in the Java heap, another problem is that they need to be contiguous, and there's fragmentation in the heap...

Btw, I think there should be a recompression library somewhere, it might be worth looking for it.

**Comment by msm595** [comment]
That is pretty large, I think I have a solution though. JPEGs can be encoded by scanline (an image row) without loading the full input into memory at once. So in these cases you can likely still encode these massive files without filling the heap. They may already be JPGs though, and will not be subject to re-encoding in that case. I will try to find large PNG webtoons somewhere, if you have any suggests for what to use that would be appreciated.

I've added the following PR TODOs:
- Split off image encoder to a separate library (I may save this till the end of the PR)
- Move image decoding into native code (remove usage of `BitmapFactory.decodeFile`)
- Add support for per-scanline encoding of JPEGs (and investigate if WebP can be used similarly)
- Add support for per-scanline decoding of PNGs and BMP (to have data to take advantage of per-scanline encoding)

As for image recompression libraries, I found the following:
- [shaohui10086/AdvancedLuban](https://github.com/shaohui10086/AdvancedLuban) - Uses `BitmapFactory.decodeFile` and `Bitmap.compress` for compression
- [amanjeetsingh150/ImageZipper](https://github.com/amanjeetsingh150/ImageZipper) - Uses `BitmapFactory.decodeFile` and `Bitmap.createBitmap` for compression
- [zetbaitsu/Compressor](https://github.com/zetbaitsu/Compressor) - Uses `BitmapFactory.decodeFile` and `Bitmap.createBitmap` for compression
- [Tourenathan-G5organisation/SiliCompressor](https://github.com/Tourenathan-G5organisation/SiliCompressor) - Uses `BitmapFactory.decodeFile` and `Bitmap.compress` for compression

Unfortunately they all seem to be inadequate, especially given the requirements here.

**Comment by inorichi** [comment]
I think I'd use my fork of the [Image](https://github.com/inorichi/Image/tree/webp) library for this.

Implementing the compressor here has a few advantages:

* You already have libjpeg-turbo, libpng, giflib and libwebp included (although only the decoder for the latter, I removed the encoder package but it can be restored easily).
* There's already an implementation to read an image from an input stream, so you can read and decode the entire image into native memory (avoiding the Java heap memory limits).
* Less static libraries are built so apk size should be smaller.

**Comment by msm595** [comment]
On it, I'll work towards integrating with the Image library.

**Comment by marcandjulien** [comment]
Hi! I want to piggyback on your PR to know if it's possible to implement a live recompression/resizing of local manga. I have a high res collection that I sync on Tachiyomi via the local folder and many become unreadable on Tachiyomi. (There is dot all over the images...) I was thinking of adding an options where you can recompress image on the fly. Let me know what you think... It's something missing for me and I could work on it this summer...

**Comment by msm595** [comment]
I think it'd be cool to have some options that do on-disk recompression and resizing of images to save disk space (though ultimately up to @inorichi). I'd let this PR die and start from scratch though. Both Tachiyomi and the nativelib used for image decoding/encoding [seven332/Image](https://github.com/seven332/Image) have both had some major changes since this PR. You possibly also need to make sure @inorichi 's PR lands (https://github.com/seven332/Image/pull/7) or use his branch of Image.

**Comment by joseph619** [comment]
What's the progress on this?

**Comment by arkon** [comment]
I know it's been a while, but I'm going to close this since it'd be more advantageous to archive the images (i.e. throw them all in a ZIP), since it's better to have a single file as opposed to multiple small-ish ones (which Android doesn't seem to handle particularly well in terms of compacting space).

SY does have it implemented, so maybe it'll make its way to the main app someday.

I'll leave the associated issue open.

**Pull request closed without merging**
