### PR TITLE
Filter by estimate update interval

### PR DESCRIPTION
**Pull request by quangkieu**
Current design for looking late, drop, or filter on update interval
Depend on
- https://github.com/tachiyomiorg/tachiyomi/pull/5734

### Images

<details>
<summary>Details</summary>

image

</details>

### CODE REVIEW

**Comment by arkon** [comment]
You'll have to rebase against the `expected-updates` branch btw, that's where I'm cleaning up some of the stuff related to this feature.

**Comment by arkon** [comment]
I didn't actually mean to close this, it got automatically closed due to how the branches were targeted/deleted. Can you reopen it against `master`?

**Comment by quangkieu** [comment]
So I wonder should I keep the filter approve or change to some tag, or display badge or something else?

**Comment by arkon** [comment]
I'm hesitant to add a bunch of filters even after having used the estimated update interval feature for a while now. 

I think we could narrow it down to a single filter like "Recently fetched" (or checked? We might need to figure out better terminology across the app for updates) with some arbitrary cutoff (30 days?) that can be used without specifically being about the estimated update interval feature.

**Comment by arkon** [comment]
Superseded by 028da099ddf42b8b305afad04aba5f819a8ce24c; we'll just have a filter for anything with a customized update frequency or not for now.

**Pull request closed without merging**
