### PR TITLE
Adapt App Themes to M3 Color System

### LINKED ISSUE #6229: Certain themes using wrong color for selected navbar item
### Steps to reproduce

Use Tako, Green Apple, Teal & Turquoise, Yin & Yang

(issue also in light theme)

### Expected behavior

Use same color as buttons, loading spinners

Screenshot_20211114-152456
Screenshot_20211114-152518
Screenshot_20211114-152536
Screenshot_20211114-152554

### Actual behavior

Screenshot_20211114-152115
Screenshot_20211114-152135
Screenshot_20211114-152149
Screenshot_20211114-152206

### Crash logs

_No response_

### Tachiyomi version

r3950

### Android version

A11

### Device

Redmi Note 9 Pro

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ivaniskandar**
Closes #6229

For non-dynamic themes, default framework text colors are still hardcoded to the Material default neutral palette (Related: https://github.com/material-components/material-components-android/issues/2449)

## Previews
| | Light | Dark |
| ------- | ------- | ------- |
| Default | image | image |
| Midnight Dusk | image | image |
| Strawberry Daiquiri | image | image |
| Yotsuba | image | image |
| Tako | image | image |
| Green Apple | image | image |
| Teal & Turquoise | image | image |
| Yin & Yang | image | image |

### CODE REVIEW

**Comment by ivaniskandar** [comment]
FYI I completely butchered pretty much all existing themes with this PR, so I'll need a hand from the original creator of each theme to do the final adjustments.

**Comment by vengiare** [comment]
Closes #6229, #6231

**Comment by ztimms73** [comment]
I'm original creator of Yotsuba theme. I see that the main color has become closer to brown. I suggest making the primary color `#AE3200` instead of `#9C4319`.

**Comment by ivaniskandar** [comment]
> I'm original creator of Yotsuba theme. I see that the main color has become closer to brown. I suggest making the primary color `#AE3200` instead of `#9C4319`.

Can you try your preferred color with [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/)? It generates all the color values needed, so it would be great to have your preferred key colors as the input.

**Comment by ztimms73** [comment]
> Can you try your preferred color with [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/)? It generates all the color values needed, so it would be great to have your preferred key colors as the input.

Sure. Primary - `#AE3200`, Secondary - `#AE3200`, Tertiary - `#6B5E2F`, Neutral - `#655C5A`

**Pull request merged**
