### PR TITLE
New Theme Tidal Wave

### PR DESCRIPTION
**Pull request by NahutabDevelop**
Added a new strong blue theme appearance to Tachiyomi titled Tidal Wave based off of the Midnight Dusk theme. 

This is in response to issue/feature request #7737 

Dark Mode Screenshots:
Tidalwave1
Tidalwave2
Tidalwave3
Tidalwave4

Light Mode Screenshots:

LTidalWave1
LTidalWave2
LTidalWave3
LTidalWave4

### CODE REVIEW

**Comment by arkon** [comment]
Can you add screenshots to the PR description?

**Comment by NahutabDevelop** [comment]
Updated PR description with Light and Dark mode screenshots.

**Comment by arkon** [comment]
Paging resident colour nitpicker @CrepeTF for review

**Comment by CrepeTF** [comment]
Not enough contrast on the active icon for the navigation menu in light mode imo. Everything else looks fine to me

**Comment by CrepeTF** [comment]
Not really the icon of course but the active selector pill

**Comment by NahutabDevelop** [comment]
Updated the tertiary color and active selector pill color in recommendation with CrepeTF.

image
image

**Pull request merged**
