### PR TITLE
Added Reverse portrait to reader

### PR DESCRIPTION
**Pull request by sahaab**
Simply added a reverse portrait option to reader.
My own issue it was.

### CODE REVIEW

**Comment by CrepeTF** [comment]
What the

**Comment by sahaab** [comment]
> What the

My charger wire keeps getting bent while reading and charging phone :p

**Comment by FourTOne5** [comment]
> > What the
> 
> My charger wire keeps getting bent while reading and charging phone :p

Well... Did you compile and test the apk?

**Comment by sahaab** [comment]
> > > What the
> > 
> > 
> > My charger wire keeps getting bent while reading and charging phone :p
> 
> Well... Did you compile and test the apk?

Yep it worked on my phone (Xperia 5 ii, android 12)

**Review by ghostbear — CHANGES_REQUESTED** [review]
You will need to add the string to the reader setting screen, in between `R.string.rotation_portrait` and `R.string.rotation_landscape`

https://github.com/tachiyomiorg/tachiyomi/blob/538478cac811655b077716383b1598db8de5e4dc/app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt#L78-L84

**Comment by sahaab** [comment]
> You will need to add the string to the reader setting screen, in between `R.string.rotation_portrait` and `R.string.rotation_landscape`
> 
> https://github.com/tachiyomiorg/tachiyomi/blob/538478cac811655b077716383b1598db8de5e4dc/app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt#L78-L84

Thank you, I have added it

**Comment by arkon** [comment]
Merged as 87ae86e1be64614674de7db9b18c50419bafcb57

**Pull request closed without merging**
