### PR TITLE
Settings: M3 and two pane ui

### LINKED ISSUE #7038: Tablet Settings should be divided in two
### Describe your suggested feature

Some apps take advantage of the tablet ui and use two columns. For example on Samsung settings the screen is divided in two colums like this:

Screenshot_20220428-154913_Settings

Maybe Tachiyomi could do the same like this mockup:

Screenshot_20220428-111133_Tachiyomi

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ivaniskandar**
Closes #7038
image

### CODE REVIEW

**Comment by AntsyLich** [comment]
Closes #7038

**Comment by arkon** [comment]
Isn't it going to be pretty awkward having only settings have the large top app bar?

**Comment by ivaniskandar** [comment]
It is but one at a time I guess?

**Comment by arkon** [comment]
I'd rather keep it relatively visually cohesive for a stable release at least.

**Comment by ivaniskandar** [comment]
Alright updated

**Pull request merged**
