### PR TITLE
Tracking: replace tick with button

### PR DESCRIPTION
**Pull request by OncePunchedMan**
If wanting to add a manga to a tracker and it showing only one result, users thought it might automatically select this item. The tick will now appear after selecting an item:

- not having an item selected doesn't show the tick

- selecting an item enables tick

### CODE REVIEW

**Comment by arkon** [comment]
I think it was actually proposed at one point, but maybe we should just have a long button at the bottom similar to the default file picker, which would be disabled until something's selected. It seems a bit more intuitive than the current menu item.

**Comment by OncePunchedMan** [comment]
sure

**Comment by OncePunchedMan** [comment]
sure

**Comment by OncePunchedMan** [comment]
Screenshot_20210824_024525

**Comment by vengiare** [comment]
Why is the button enabled when nothing is selected tho

**Comment by OncePunchedMan** [comment]
still WIP

**Comment by Riztard** [comment]
> still WIP

make it a draft?

**Comment by OncePunchedMan** [comment]
this ones ready for merging now

Screenshot_20210824_160924

Screenshot_20210824_160929

**Comment by vengiare** [comment]
Why's it invisible when disabled tho

> Should be greyed out

**Comment by OncePunchedMan** [comment]
Screenshot_20210824_160924

Screenshot_20210824_160929

**Pull request merged**
