### PR TITLE
Add sui support

### PR DESCRIPTION
**Pull request by D34DPlayer**
Sui is a Magisk module that provides the Shizuku API for rooted devices and will eventually replace Shizuku for those.
As of right now, you can only choose the Shizuku installer if the Shizuku application is installed, so I tweaked the check to also look for Sui.

### CODE REVIEW

**Comment by arkon** [comment]
I'm not super familiar with Shizuku or Sui. Do we need to update the wording in the app to reflect both at some point?

**Comment by D34DPlayer** [comment]
Right now, if neither Shizuku or Sui are installed, a popup appears explaining how to install Shizuku.

I think this behavior should be kept as Shizuku is easier to install, and once installed it'll inform root users about Sui anyways.

The only thing that I guess could be changed is renaming Shizuku to Shizuku API in the selection field.

**Comment by ivaniskandar** [comment]
Is this tested? Referring to the API guide it's missing the init call.

**Comment by arkon** [comment]
It's actually automatically initialized by Shizuku: https://github.com/RikkaApps/Shizuku-API/blob/58e25c450800bf56791eaaaa88fdb1afbfb30b97/provider/src/main/java/rikka/shizuku/ShizukuProvider.java#L167

**Comment by ivaniskandar** [comment]
Ah you're right. It's all good then

**Pull request merged**
