### PR TITLE
confirmation mark as read/unread in library

### LINKED ISSUE #5100: [Feature Request] confirm mark as read/unread in library
## Why/User Benefit/User Problem
people may accidentally press wrong button like mark as read/unread

## What/Requirements
add confirmation to continue for mass mark as read/unread or undo button

image

### PR DESCRIPTION
**Pull request by Riztard**
add dialog confirmation for mark as read/unread in library
lol i manage to add it myself 
Closes #5100

<table>
<tr>
	<td>
	<td>
</table>

### CODE REVIEW

**Comment by joseph619** [comment]
Seems annoying to do this for individual chapters

**Comment by CrepeTF** [comment]
If you've already committed to go into action select mode wouldn't that in itself be a confirmation? And on top of that you need to actually select read/unread

**Comment by CrepeTF** [comment]
It might make more sense to have an undo snackbar instead

**Comment by arkon** [comment]
Agreed, undo would be less annoying.

**Pull request closed without merging**
