### PR TITLE
Novel

### PR DESCRIPTION
**Pull request by DeentheFair**
Can you guys add novel features in aniyomi?

  If your changes are visual, please provide images below:

### Images
| Image 1 | Image 2 |
| ------- | ------- |
|  |  |
-->

### CODE REVIEW

**Comment by AntsyLich** [comment]
Wrong repo. This isn't Aniyomi.

**Comment by CrepeTF** [comment]
Most intelligent aniyomi user:

**Comment by DeentheFair** [comment]
And how is that?

**Comment by CrepeTF** [comment]
Look at the very top it says **tachiyomiorg/Tachiyomi**, not Aniyomi or anything of the sort. We neither are nor affiliated with Aniyomi.

Also a Pull Request ≠ Feature Request.

**Comment by DeentheFair** [comment]
My bad this is the first time I use this blog and I want novel features that bad that I didn't think to the end

**Comment by DeentheFair** [comment]
How I gonna delete this

**Pull request closed without merging**
