### PR TITLE
Requests: add `GET(HttpUrl)` overload

### PR DESCRIPTION
**Pull request by stevenyomi**
Many extensions use `HttpUrl.Builder` to build a search request. This overload allows them to do `GET(urlBuilder.build(), headers)` instead of `GET(urlBuilder.toString(), headers)`, saving an unnecessary URL parse.

OkHttp's `Request.Builder.url(String)` silently converts WebSocket URLs to HTTP ones, but we don't actually need that, so doing `url.toHttpUrl()` should be safe.

### CODE REVIEW

**Comment by AntsyLich** [comment]
Open a PR in [tachiyomiorg/extensions-lib](https://github.com/tachiyomiorg/extensions-lib) too

**Comment by stevenyomi** [comment]
Done: https://github.com/tachiyomiorg/extensions-lib/pull/7.

**Comment by arkon** [comment]
Any reason you're not also adding it for the other methods?

**Comment by stevenyomi** [comment]
> Any reason you're not also adding it for the other methods?

In most cases, people need to manually build the URL (path, queries, fragments) with proper escaping only for GET requests. You usually POST, PUT, etc, to static URLs - string concatenations should be sufficient.

**Pull request merged**
