### PR TITLE
For library update error log, group errors by error string, and then sort the resulting list by source

### PR DESCRIPTION
**Pull request by FlaminSarge**
Format is e.g.
```
! Error 1
  # Source 1
    - Manga 1
! Error 2
  # Source 1
    - Manga 5
  # Source 2
    - Manga 2
    - Manga 3
  # Source 3
    - Manga 4
```

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Another option is
```
Error 1
- Source 1
  - Manga 1
```
Thoughts?

**Comment by CarlosEsco** [comment]
My vote is the 2nd one

**Comment by FlaminSarge** [comment]
Updated to the following:
```
! Error
  # Source
    - Manga
```

**Comment by FlaminSarge** [comment]
Screenshot_1626786832
Here it is in action.

**Comment by arkon** [comment]
Maybe they should be sorted too? That way at least the different source not installed errors will be grouped together, despite having an entry per ID.

**Comment by FlaminSarge** [comment]
As a followup I was going to try to group specifically those. Thoughts?

**Comment by arkon** [comment]
I'm fine with that.

**Pull request merged**
