### PR TITLE
add Theme "Teal & Turquoise"

### PR DESCRIPTION
**Pull request by Riztard**
<table>
<tr>
	<td>Light
	<td>Dark
	<td>Pure Black
<tr>
	<td>
	<td>
	<td>
<tr>
	<td>
	<td>
	<td>
<tr>
	<td>
	<td>
	<td>
</table>

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Taking my old pr now too? smh

**Comment by Riztard** [comment]
> Taking my old pr now too? smh

who want to check pr history for color smh

**Comment by Soitora** [comment]
Your ripple_colored feels too strong, definitely uses a much brighter value than other themes

**Comment by Riztard** [comment]
> Also, the name is kinda 🤡

then what? sunny beach? sunny ocean? ocean?

**Comment by Soitora** [comment]
> > Also, the name is kinda 🤡
> 
> then what? sunny beach? sunny ocean? ocean? tropical beach?

image
*insert KekW here*

Lowkey like "Blue Lagoon"
image

**Comment by Soitora** [comment]
> I prefer teal. Since there is no theme preview. Blue lagoon makes it seem like a blue theme

A lagoon is pretty Turqoise-ish, and I think @Riztard original point with multi name is due to the dark/light mode being different, so one is teal and other is turqoise

**Comment by Riztard** [comment]
it seems turquoise is a gemstone, so yea just `Teal & Turquoise`

**Comment by arkon** [comment]
Your screenshots are showing incorrect status/navbar colours. Is that actually the case?

**Comment by Soitora** [comment]
> Your screenshots are showing incorrect status/navbar colours for the dark themes. Is that actually the case?

Based on what I see is changed I think it's safe to assume it's the emulator and not actual behavior

**Comment by Riztard** [comment]
yea just emulator thing

**Pull request merged**
