### PR TITLE
Add theme "Kinda Purple"

### PR DESCRIPTION
**Pull request by CrepeTF**
Adds the theme "Kinda Purple"

### Images

**Library**
| Dark theme | Light theme |
| ------- | ------- |
| image | image |

**Library filter**
| Dark theme | Light theme |
| ------- | ------- |
| image | image |

**More**
| Dark theme | Light theme |
| ------- | ------- |
| image | image |

**M2 Switches**
| Dark theme | Light theme |
| ------- | ------- |
| image | image |

### CODE REVIEW

**Comment by CrepeTF** [comment]
**Updated screenshots**
| Library| Settings category titles |
| ------- | ------- |
| image | image |

**Comment by CrepeTF** [comment]
**Updated screenshots**
| Library |
| ------- |
| image |

**Comment by arkon** [comment]
@Osyx FYI, in case you wanted to provide some input. Not sure if the two of you want to consolidate your efforts into The Ultimate Purple Themes or something.

**Comment by Osyx** [comment]
Haha, I like it! The dark theme seems more like a "kinda pink" dark theme than purple though, imo. I would've expected the dark variant to use something similar to the primary color of the light one as the background/surface. 
Feel free to check my PR and leave some comments as well Crepe, #7343!

**Comment by CrepeTF** [comment]
Closing in favour of #7343

**Pull request closed without merging**
