### PR TITLE
Tweak Midnight Dusk colors

### PR DESCRIPTION
**Pull request by OncePunchedMan**
Dark | Pure Black
---|---
Screenshot_20211207_103822 | Screenshot_20211207_103737
Screenshot_20211207_103825 | Screenshot_20211207_103810
Screenshot_20211207_103831 | Screenshot_20211207_103749

I don't think light theme needs tweaking.

### CODE REVIEW

**Comment by OncePunchedMan** [comment]
true, i thought i did. leemme change it

**Comment by Riztard** [comment]
change the pink to hot pink as well :D

**Comment by OncePunchedMan** [comment]
_i'd totally not be stealing tfs theme then_

**Comment by Riztard** [comment]
also no tweak for light mode?

**Comment by OncePunchedMan** [comment]
>I don't think light theme needs tweaking.

**Comment by OncePunchedMan** [comment]
just my emulator being a bich. and i even said i won't trust it..

**Comment by CrepeTF** [comment]
I approb bb

**Comment by ghostbear** [comment]
image

Maybe tweak the brownish color in light mode to be similar to the green in dark mode. This would also make this theme slightly more different than Starberry Daiquiri

**Pull request merged**
