### PR TITLE
Add toggleable unread count badge to Updates bottom bar

### LINKED ISSUE #5544: Updates tab badge for new chapters
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

When there are new updates to a manga, the Updates tab of the bottom bar would have a badge on it, (identical to how the Browse tab can show the number of extension updates) indicating the number of new chapters.

### Other details

This might be good to have as a toggle-able feature in settings as well, so people don't have to constantly live with the indicator if they don't immediately read new chapters.

### PR DESCRIPTION
**Pull request by datreesezcup**
The badge indicates how many unread chapter updates there are to read

There is also a setting to hide this badge:
Settings -> Library -> Global update -> Show update count on bottom bar

Closes #5544 (my own issue lol)

--------

update_badge_preview

### CODE REVIEW

**Comment by arkon** [comment]
I do wonder if this is kind of misleading, given Updates doesn't actually show _everything_.

**Comment by datreesezcup** [comment]
> 
> 
> I do wonder if this is kind of misleading, given Updates doesn't actually show _everything_.

I'm afraid I don't understand. By not showing everything, do you mean because the updates tab only shows updates within the last 3 months? Or something else?

I suppose this feature could be a tiny bit confusing the _very first time_ a user sees it, but I'd imagine as soon as they see the correlation between the badge count and number of unread updates, they'd figure it out.

Or have you been referring to something else entirely?

**Comment by arkon** [comment]
2 things:
- the 3 month cutoff
- chapters without a date don't show up here

The second one may be worth addressing somehow though, although it's been tried before albeit with some weird side effects.

**Comment by AqilCont** [comment]
Will this ever be added? I honestly want this feature even if it isn't perfect o.o

**Pull request merged**
