### PR TITLE
Fix UpdateCategories dialog to not remove old value

### PR DESCRIPTION
**Pull request by quangkieu**
Fix https://github.com/tachiyomiorg/tachiyomi/issues/961
Add preselected to updateCategoriesForMangas listener as reference
Add updateMangasToCategories that bulk update categories of mangas using
    old and new common categories

Signed-off-by: Quang Kieu <quangkieu1993@gmail.com>

### CODE REVIEW

**Comment by quangkieu** [comment]
@arkon I wonder who I need to ping for review?

**Comment by arkon** [comment]
Nobody, I'll look at it eventually.

**Comment by quangkieu** [comment]
Hopefully fixed forked branch too https://github.com/Jays2Kings/tachiyomiJ2K/issues/644

**Comment by CarlosEsco** [comment]
Copying this from the J2K ticket
```

    Set one comic in both A, B catalogs
    Set another comic in both A, C catalogs
    Select both comics, the catalog menu would show A checked
    Now add catalog D
    Both comics now have tag A, D but none of them have catalog B or C
```
So while #961 is an issue, solving it this way just pushes the issue to the other extreme.

Glancing at the code, it keeps the uncommon categories on each manga, but what if i wanted to remove the uncommon ones also?.  Like if i had manga in A,B,C and some of them were also in D, and wanted to move them all the E this wouldnt work.

**Comment by quangkieu** [comment]
@CarlosEsco 
User could search for category D
Then select all comic filtered
D should now be checked initially
Remove D and apply

**Comment by quangkieu** [comment]
This is not ideal solution as this is based on dialog with only 2 states
But it would not completely remove old uncommon

**Comment by arkon** [comment]
I'm having trouble wrapping my head around how this is _supposed_ to work given the change. Neither the steps that @CarlosEsco nor @quangkieu described are intuitive.

The dialog would need to be reworked with a custom view with a tri-state dialog that shows:
- [✓] Checked if all manga are in that category
- [-] Mixed state if some, but not all, manga are in that category
- [ ] Not checked if no manga are in that category

And clicking a checkbox would go to:
- [✓] All manga should be in this category
- [ ] No manga should be in this category

Where categories with the mixed state ([-]) would not be changed if not toggled.

**Comment by quangkieu** [comment]
@arkon I fully understand that. I just not know how to set the [-]. If you could point to the document or code for that. I am familiar with Kotlin or Android much

**Comment by arkon** [comment]
Unfortunately it won't be that straightforward in the code's current state, since it'd involve creating a new view to mimic the checkbox with an extra state.

We have something similar that we use for the filter sheets (it uses different drawables for the state) that you can refer to: https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/widget/ExtendedNavigationView.kt#L93

**Comment by quangkieu** [comment]
@arkon Hmm, I would try to see if I could catch up on it. In the meantime, I wonder if we could push this one out so it would be least destruction to the Library. I would assume user would able to work around the quirk behavior.

**Comment by arkon** [comment]
I have tri-state checkbox dialogs implemented for category exclusion settings, so I'll reuse that for addressing this at some point.

**Pull request closed without merging**
