### PR TITLE
Add new line check to user agent preference

### LINKED ISSUE #7856: Don't allow new line at the end of user agent string
### Steps to reproduce

1. Go to settings > advanced > Default user agent string
2. put a new line at the end of the string
3. restart the app
4. go to browse tab which crashes the app

### Expected behavior

It should not let the user add a new line at the end

### Actual behavior

It lets the user add a new line at the end, leading to crash

### Crash logs

E AndroidRuntime: java.lang.IllegalArgumentException: Unexpected char 0x0a at 117 in User-Agent value: Mozilla/5.0 (Linux; Android 9; SM-G955F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36

### Tachiyomi version

0.13.6 and r4821

### Android version

Android 12

### Device

Tecno Spark 6 (with custom aosp rom)

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mobi2002**
closes #7856

It is my first time contributing to tachiyomi so please tell me if something is wrong.

### CODE REVIEW

**Comment by vetleledaal** [comment]
I think silently trimming the input would be better

**Comment by vetleledaal** [comment]
Using `.trim()` is fine in this case, it strips `\n` along with all other whitespace characters as defined in Unicode.

I haven't worked on the main app, just extensions, so not sure where you would make the change. Maybe someone else could chime in.

**Comment by mobi2002** [comment]
Honestly, I don't know enough kotlin to figure out the code base. I tried to make sense of it but I still need time, so I am just gonna close this pr.

**Comment by nzoba** [comment]
I think you could just replace the `onChange` method by something like that:

```
if (it.toString().isBlank()) {
    activity?.toast(R.string.error_user_agent_string_blank)
} else {
    text = it.toString().trim()
    activity?.toast(R.string.requires_app_restart)
}
false
```

You manually set the text with the trimmed value and then you return false to deny the input value (otherwise it will override the manually set value)

**Pull request closed without merging**
