### PR TITLE
Translations (Continuous)

### PR DESCRIPTION
**Pull request by j2ghz**
**Merge just before next release** or when there's a significant amount of translations waiting
**Don't** merge if push healthcheck is not up: [Healthcheck](https://healthchecks.io/checks/9d0ad96f-ea6f-470d-911a-17ac190c5fec/details/)
Continues from #4204

More information: https://tachiyomi.org/help/contribution/#translation
[Translation status](https://hosted.weblate.org/engage/tachiyomi/)

### CODE REVIEW

**Comment by ghostbear** [comment]
It seems that people are able to translate tracker name even though they are flagged as not translatable like `app_name`
```xml
<string name="tracker_anilist" translatable="false">AniList</string>
<string name="tracker_myanimelist" translatable="false">MyAnimeList</string>
<string name="tracker_kitsu" translatable="false">Kitsu</string>
<string name="tracker_bangumi" translatable="false">Bangumi</string>
<string name="tracker_shikimori" translatable="false">Shikimori</string>
```

**Comment by j2ghz** [comment]
Interesting. Both https://github.com/j2ghz/tachiyomi/blob/translations/app/src/main/res/values/strings.xml#L3 and https://github.com/j2ghz/tachiyomi/blob/translations/app/src/main/res/values/strings.xml#L565 look the same but only the app name is not translatable on weblate. I think @arkon or @Soitora were solving some issues related to that previously.

**Comment by arkon** [comment]
Old issue: https://github.com/WeblateOrg/weblate/issues/4171

New issue opened: https://github.com/WeblateOrg/weblate/issues/5268

**Comment by Soitora** [comment]
> Old issue: [WeblateOrg/weblate#4171](https://github.com/WeblateOrg/weblate/issues/4171)
> 
> New issue opened: [WeblateOrg/weblate#5268](https://github.com/WeblateOrg/weblate/issues/5268)

For now I just manually set their flags in **Weblate** as `read-only`

**Pull request merged**
