### PR TITLE
Feature to allow mangas to be linked to each other

### PR DESCRIPTION
**Pull request by Gfadebayo**
This PR allows mangas to be linked.

Linking allows for easy movement between mangas from the Manga detail screen. It can also help relate mangas together. 
Linking can actually be achieved using the categories system, but there are certain situations where only 2 mangas might want to be linked which can happen a lot, so creating a new category just for each of these situations can be overkill.

### Images
| Link action menu displayed in selection mode | Link badge displayed on linked mangas | 
| ------- | ------- |
| Screenshot_1 | Screenshot_2 |

| Unlink action menu displayed in selection mode | Links displayed in Manga detail screen for easy movement | 
| ------- | ------- |
Screenshot_3 |Screenshot_5

| Link backup |
| --- |
Screenshot 6

### CODE REVIEW

**Comment by AntsyLich** [comment]
Add merging too (as a separate pr)

**Comment by arkon** [comment]
I'm not interested in entry merging in the main app.

I'm also a bit hesitant on this linking since it feels like subcategories would be more flexible?

**Comment by Gfadebayo** [comment]
> Add merging too (as a separate pr)

Sorry I don't get you. Do you mean a new feature?

**Comment by Gfadebayo** [comment]
> I'm not interested in entry merging in the main app.
> 
> I'm also a bit hesitant on this linking since it feels like subcategories would be more flexible?

There's no merging being done, linked mangas still exists independently in their categories. The main attraction right now is allowing users to easily jump to another manga from the manga detail screen. I think if jumping can be available with the categories system this can be discarded, but there's the other example I gave where a user might just want to relate 2 mangas together and creating a new category might be overkill

**Comment by Gfadebayo** [comment]
> I'm not interested in entry merging in the main app.
> 
> I'm also a bit hesitant on this linking since it feels like subcategories would be more flexible?

Is a subcategory feature being worked on? If it is similar I guess this can be discarded

**Comment by arkon** [comment]
> Sorry I don't get you. Do you mean a new feature?

Feel free to ignore him, it's not related to this PR.

> Is a subcategory feature being worked on? If it is similar I guess this can be discarded

It's an old request (#1803), but nobody's worked on it.

**Comment by Gfadebayo** [comment]
> > Sorry I don't get you. Do you mean a new feature?
> 
> Feel free to ignore him, it's not related to this PR.
> 
> > Is a subcategory feature being worked on? If it is similar I guess this can be discarded
> 
> It's an old request (#1803), but nobody's worked on it.

Oh I see what you mean, I'll try modifying this to a subcategory feature instead

**Pull request closed without merging**
