### PR TITLE
ChapterSourceSync: set default timestamp to max timestamp

### LINKED ISSUE #7162: ChapterSourceSync: add fallback upload date logic
### Describe your suggested feature

Some sources only provide upload date of the lastest chapter. In this case, extensions either have to ignore it, or falsely set upload date of all existing chapters to it: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9242

Adding a fallback upload date will solve this issue:
```kotlin
// only needed for SChapter etc, not needed for db Chapter
val upload_date_fallback: Long?
```

And fallback new chapters' upload date to it:
https://github.com/tachiyomiorg/tachiyomi/blob/6580f5771f634b0e2c25f8cd42fa1596b2ea4e1c/app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt#L72-L76
```diff
-   sourceChapter.date_upload = Date().time
+   sourceChapter.date_upload = (???).date_upload_fallback ?: Date().time
```

so that extensions may set it to the known upload time and `upload_date = 0` when parsing chapters to avoid falsely updating all existing chapters to the lastest upload time, bypassing this check:
https://github.com/tachiyomiorg/tachiyomi/blob/6580f5771f634b0e2c25f8cd42fa1596b2ea4e1c/app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt#L87-L89

The update logic seems to be using a db Chapter object, and I think it's unnecessary to add such field to it. Not sure how to implement this.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by kasperskier**
Closes #7162.

Replaces #7192, see the discussion there.

Solves the dilemma that if source only provides upload date of the latest chapter, extension has to either set it to all chapters or none. Now extensions can set that date to the latest chapter, and new chapters with timestamps of 0 will be set to that one instead of right now.

**The maximum is scoped to chapters before (i.e. newer than) the current one that are not in the database.** This might help to avoid some edge cases.

~~I also changed the `readded` List to Set according to the IDE's prompt because it is later subtracted from two Lists, where Set has better performance.~~ Suppressed that problem, see #6372.

- [ ] If this gets merged, add it to extension repo's [CONTRIBUTING.md](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by FourTOne5** [comment]
>I also changed the readded List to Set according to the IDE's prompt because it is later subtracted from two Lists, where Set has better performance.

Revert revert fuckin revert it right now

**Comment by kasperskier** [comment]
> > I also changed the readded List to Set according to the IDE's prompt because it is later subtracted from two Lists, where Set has better performance.
> 
> Revert revert fuckin revert it right now

Okay but could you please explain politely?

**Comment by FourTOne5** [comment]
> > > I also changed the readded List to Set according to the IDE's prompt because it is later subtracted from two Lists, where Set has better performance.
> > 
> > 
> > Revert revert fuckin revert it right now
> 
> Okay but could you please explain politely?

https://github.com/tachiyomiorg/tachiyomi/pull/6372

**Comment by kasperskier** [comment]
@FourTOne5 Reverted. I also added comment and suppressed the problem.

Is it a bad implementation of `hashCode()` or something else?

**Comment by arkon** [comment]
Can you submit a PR for the extension repo doc change too?

**Comment by kasperskier** [comment]
> Can you submit a PR for the extension repo doc change too?

Will do.

**Pull request merged**
