### PR TITLE
More themes cleanup

### LINKED ISSUE #2907: Dialog UI Inconsistencies
### Device information
* Tachiyomi version: dev r2081
* Android version: 8.1.0

### Other details
I saw two different dialog ui in the app. 

The first style (which is used more) has
- a dark background scrim
- items/choices don't have an active effect
- buttons have a blue active effect
1st-x
1st-y

The second style (which is used less) has
- a dark**er** background scrim
- items/choices have an active effect
- buttons have a gray active effect
2nd-x
2nd-y

Here are all the dialogs I saw:
First style:
- Misc > Extensions > [Any extension] > [Any option with a dialog]
- Misc > Settings > General > Start screen
- Misc > Settings > General > Language
- Misc > Settings > General > App theme
- Misc > Settings > General > Light theme variant
- Misc > Settings > General > Dark theme variant
- Misc > Settings > Library > Library update frequency
- Misc > Settings > Library > Library update restrictions
- Misc > Settings > Library > Categories to include in global update
- Misc > Settings > Library > Library update order
- Misc > Settings > Library > Default category
- Misc > Settings > Reader > Default viewer
- Misc > Settings > Reader > Scale type
- Misc > Settings > Reader > Zoom start position
- Misc > Settings > Reader > Rotation
- Misc > Settings > Reader > Background color
- Misc > Settings > Reader > Double tap animation speed
- Misc > Settings > Reader > Side padding
- Misc > Settings > Backup > Backup frequency
- Misc > Settings > Backup > Max automatic backups

Second style:
- [Any selected manga] > Move to categories
- Misc > Source Migration > [Any source] > [Any manga] > [New source] > Select data to include
- Misc > Settings > Library > Library manga per row
- Misc > Settings > Library > Edit categories > Add/Edit category
- Misc > Settings > Downloads > Download location
- Misc > Settings > Tracking > Log in to MyAnimeList/Kitsu
- Misc > Settings > Backup > Create Backup
- Misc > Settings > About > Version
- Misc > Settings > About > Build time 

- \+ [Any selected manga] > [Add tracking]
- \+ [Any selected manga] > [Any tracking provider] > Status / Chapters / Score

### LINKED ISSUE #5154: [Bug] Missing places for Ripple
# Unfixed

## No results found
Related file: [`EmptyView.kt` #L60](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/widget/EmptyView.kt#L60)
Setting `setRippleColorResource` works but it requires a Color and not just the theme color attribute.

| No results found |
| --------------------------- |
|  |

Both of the images below are affected somewhat by `Theme.Widget.Button.Action`.
This style is imported here on [`EmptyView.kt` #L46](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/widget/EmptyView.kt#L46)

Except I can't find a way to actually set it for the `EmptyView` one.

| EmptyView | Library Buttons |
| ---------- | ------------------- |
| EmptyView | Library Buttons |

## Material dialogs buttons
After hours of testing, I've yet to manage to succeed with this.
| Material dialogs buttons |
| --------------------------- |
|  |

# Fixed

## Dialog highlight
Fixed by #5197.

## Source filter dropdown
Fixed by #5197.

## Tracker login pw revealer
Fixed by #5197.

## Download cancel/etc dialog
Fixed by #5197.

### PR DESCRIPTION
**Pull request by ivaniskandar**
~~This should have no user-visible changes~~
- Changed tracker login button color
- Changed text color when "comfortable" style library item is selected
- Unified background dim amount for modals
- Tweaked ripple/selection color (resolves #5154, resolves #2907)

### CODE REVIEW

**Comment by arkon** [comment]
Is this actually ready, or still a WIP?

**Comment by Soitora** [comment]
I think it's actually ready now, I checked everything from his branch I possibly could get myself to test

Worth to note is that all ripples are now colored, I am personally very unsure if looks right or not so I'll leave that to someone else to chip in on.

**Comment by ivaniskandar** [comment]
> Is this actually ready, or still a WIP?

For me it's ready, recent commits was pushed in response to @Soitora's feedback.

**Comment by arkon** [comment]
Whoops, there's a merge conflict now.

I'll just merge this (when fixed) and can iterate if needed.

**Pull request merged**
