### PR TITLE
Added "Yotsuba" theme

### PR DESCRIPTION
**Pull request by ztimms73**
From the moment when colorful themes were added to the app, I will also add my own contribution to this. I would like to have an orange-pinkish theme implemented in the app, the color was taken from the hair color of the character Yotsuba Nakano from the manga "5-toubun no Hanayome". As for me, the theme looks juicy.

Screenshot_1622723198

### CODE REVIEW

**Comment by AviKav** [comment]
This is Mangadex

**Comment by ztimms73** [comment]
> This is Mangadex

I don't really see the colors of MangaDex here, where it is represented by a pure orange color

**Comment by specterflare** [comment]
Indeed. "Mangadex orange" is `#f7931e`, while this is `#fc8c5c`.

**Comment by specterflare** [comment]
Could someone please review/merge this? I really want to use it.

**Pull request merged**
