### PR TITLE
Ignore gradle.properties.swp

### PR DESCRIPTION
**Pull request by d-najd**
The file is from intellij vim plugin if I remember correctly, 
I accidentally included it once (and nearly did again 5min ago) with a commit and I remember seeing another commit from arkon removing it after (sorry about that).

### CODE REVIEW

**Comment by arkon** [comment]
Could just ignore all swap files.

**Comment by stevenyomi** [comment]
You can add it to `.git/info/exclude` to make Git ignore it locally.

**Comment by d-najd** [comment]
> You can add it to `.git/info/exclude` to make Git ignore it locally.

that will work but if some other contributor is using vim plugin it will still generate the files and he probably wont notice, plus there are no drawbacks so why not.

**Comment by d-najd** [comment]
> Could just ignore all swap files.

sure give me a min

**Comment by stevenyomi** [comment]
> that will work but if some other contributor is using vim plugin it still might generate the file and he probably wont notice, plus there are no drawbacks so why not.

Yeah but if some other contributor is using _(insert plugin name here)_ plugin it still might generate the file and he probably wont notice, so why not add every kind of temp file into our gitignore? 😏

**Comment by stevenyomi** [comment]
Imo gitignore file should only cover commonly used temp files and individual tool generated ones should be ignored locally, otherwise the gitignore file will be filled with all kinds of files.

**Comment by d-najd** [comment]
> > that will work but if some other contributor is using vim plugin it still might generate the file and he probably wont notice, plus there are no drawbacks so why not.
> 
> Yeah but if some other contributor is using _(insert plugin name here)_ plugin it still might generate the file and he probably wont notice, so why not add every kind of temp file into our gitignore? smirk

might as well open a request to ignore _every_ possible plugin while we are at that and mark it as top priority

jokes aside I still think that we can add files to gitignore as we notice them, the decision is up to you all to make 🙂

**Pull request merged**
