### PR TITLE
Update wording of "pref_remove_after_marked_as_read"

### PR DESCRIPTION
**Pull request by FourTOne5**

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Does this need clarification?

**Comment by FourTOne5** [comment]
> Does this need clarification?

yes ~~Saying from personal experience~~

**Comment by CarlosEsco** [comment]
There is no other way to mark as read though?

**Comment by FourTOne5** [comment]
> There is no other way to mark as read though?

After reading a chapter it gets marked as read (which is done automatically)

**Comment by CarlosEsco** [comment]
The setting right below that specifies marking after reading though

**Comment by FourTOne5** [comment]
> The setting right below that specifies marking after reading though

It says `After reading automatically delete` or am I missing something?

**Comment by CarlosEsco** [comment]
Sorry mistyped. I meant the one below is obviously for the after reading delete.  So the current one is when a user marks it

**Comment by FourTOne5** [comment]
> Sorry mistyped. I meant the one below is obviously for the after reading delete. So the current one is when a user marks it

Well it doesn't bother to add a extra word to help dumb people ~~like me~~

**Pull request merged**
