### PR TITLE
[WIP] Cross-device sync

### PR DESCRIPTION
**Pull request by null-dev**
This PR implements cross-device sync between a single server and multiple clients. Do not merge this as it's a heavy WIP.

## TESTING
Please help test this PR if you have multiple devices. I only have two device myself so I cannot do any extensive testing.
### How to test
1. Download the test app onto both devices, the latest copy can be found [here](http://dl.nulldev.xyz/app-dev-debug.apk).
2. Sign up for an account here: https://tachiyomi.nd.ax/
3. Add the sync server on both devices:
    1. Launch the app and go to `Settings > Sync`. Tap on `Library sync` to enable sync.
    2. Enter the credentials provided on the website and press "log in".
4. Make changes to your library on both devices and press `Sync now` in the top menu bar (in the `My library` screen).
5. If something weird happens or the sync fails, please post a comment here.
6. Repeat steps 5-6.

Notes:
- My sync server may be slow (as it has like 1GB of RAM). If your syncs fail with `Network Error` please try again before posting here.
- The sync server is built into TachiWeb. You can find the source code for it here: https://github.com/TachiWeb/TachiWeb-Server

## TODO Before merge
- **More testing**
- ~~Add database migrations~~
- ~~Add a settings screen for sync~~
- ~~Disable clearing database while sync is enabled~~
- ~~Sync metadata is still tracked even with sync off~~ It's VERY difficult to do this properly and since the performance impact is rather small, I will not attempt to do this.
- Code cleanup
- Documentation on sync protocol
- ~~Fix datetime calculations (use correct time when applying sync report)~~
- ~~Fix server returning a too narrow range of changes (so some changes are not being distributed to clients)~~
- ~~Apply app theme in server login page~~
- ~~Add in-app sync setup UI~~
- ~~Automatically re-configure sync if system believes sync is on and app believes sync is off (possible since some sync settings are managed by system and some by the app)~~
- ~~Protocol version negotiation~~

## Possible expansions in the future:
- The sync architecture used in this PR theoretically can allow direct device-to-device syncing but both devices must be online during the sync process. Therefore, by adding something like sync over NFC, one could sync libraries by simply tapping the two devices together.

### CODE REVIEW

**Comment by j2ghz** [comment]
How are you handling conflicts?

**Comment by null-dev** [comment]
@j2ghz There will be no conflicts.

Every time you make a change, the app records the time you made that change. When running the sync, the latest change made will take precedence.

*Or, at least that's how it's supposed to work.* Your comment just made me realize that there is a bug in this particular area of the sync code which will cause the first client which syncs to take precedence instead...

I'll fix this when I have some time.

**Comment by null-dev** [comment]
Notice to testers. I've just cleared your sync data (because I've just finished the database migration code) so to ensure sync works properly again, go into `Settings > Sync` and toggle the "library sync" off then on again.

**Comment by null-dev** [comment]
Quick update:

Yes, I'm still working on this. Also, I've just pushed out a significant improvement to the sync server UI.

**Comment by AlessioAtroni** [comment]
Will this feature be available using your Google account and its related services?

**Comment by Sparh4wk** [comment]
@null-dev will you release public version as well so I can run it on my home server, or there will be only one server hosted by xx.... and yes I also thinks that this approach of not using google etc is much better

**Comment by null-dev** [comment]
It's already public: https://github.com/TachiWeb/TachiWeb-Server

There is just no documentation on self-hosting it currently... I'll write it after the rewrite of Tachiyomi is done.

I'm probably not going to merge this P.R. until the rewrite is done since once the rewrite is done I will have to rewrite this P.R. along with the sync server anyways.

**Comment by null-dev** [comment]
@xmat123x The experiment is kinda on pause as I don't want to continue development while Tachiyomi is being rewritten (as then I have to rewrite this P.R. anyways).

**Comment by codewisp** [comment]
What's current status on this?

**Comment by Sparh4wk** [comment]
@null-dev @inorichi 
I dont want it to sound rude, but any news about 1.x version? some ETA, like month, year etc? I rly miss this feature and as you will not implement it to 0.x version, I cant wait for 1.x to be finished. I know you are doing it for free etc.. and Im rly glad for this super piece of software, so dont get me wrong, Im not trying to be rude or anything :(

**Comment by inorichi** [comment]
I can't tell. Things are moving slowly and we're usually busy, but we're working on it.

**Comment by CarlosEsco** [comment]
@Sparh4wk  10 years.  1 year for every ask.

**Comment by SaruDesu422** [comment]
Any update?

**Comment by CarlosEsco** [comment]
@SaruDesu422 stop going through old issues asking for updates.

**Comment by Sparh4wk** [comment]
> 
> 
> @SaruDesu422 stop going through old issues asking for updates.

imho, this one is important and should be answered

**Comment by SaruDesu422** [comment]
@CarlosEsco I was just asking, am I not suppose to?

**Comment by CarlosEsco** [comment]
I can answer it it's abandoned for now as null has no time and is waiting for 1.x tachiyomi.  If an issue is old and never got an update then you can consider it abandoned asking in github just annoys the maintainers

**Comment by SaruDesu422** [comment]
@CarlosEsco Well, sry for not knowing about tht.

**Comment by CarlosEsco** [comment]
> @CarlosEsco Well, sry for not knowing about tht.

It's more that if there is no activity. It's pretty clear what the status is

**Comment by kakardo** [comment]
Has this been abandoned?

**Comment by serjflint** [comment]
> Has this been abandoned?

@kakardo No. Please read the discussion above. There is no 1.x.x version yet, so no update here

**Comment by lenrik1589** [comment]
I had lost all my reading progress in unfortunate event of being forced to hard reset the device wiping all the data and even though Google somehow restored the data once the unfortunate event occurred second time after which google did not restore the app data so in hope that doesn't happen to anyone else  I beg maintainers to update this pull request to help those who have a lot of data from the app not lose it in the unfortunate turn of events as I had to.

**Comment by CarlosEsco** [comment]
going to close this, as the code has changed drastically since and null is inactive

**Pull request closed without merging**
