### PR TITLE
Implement predictive back animation

### PR DESCRIPTION
**Pull request by ivaniskandar**
For home screen tabs, Navigator screens and most dialogs

### CODE REVIEW

**Comment by DevSrSouza** [comment]
Awesome work! Can we also make this a option-in extension for Voyager?

**Comment by THElegend5** [comment]
I was just about to open a feature request for this,  thanks for implementing.

**Comment by ivaniskandar** [comment]
> Awesome work! Can we also make this a option-in extension for Voyager?

@DevSrSouza Thanks and absolutely! Feel free to adapt this implementation as fits.

**Comment by arkon** [comment]
I don't know how I feel about the animation between nav bar sections, but otherwise seems good.

**Pull request merged**
