### PR TITLE
Sanitized ComicInfo fields by replacing Surrogates with the � character

### LINKED ISSUE #8537: Surrogate pair with high surrogate in string makes ComicInfo.xml generation to fail
### Steps to reproduce

1. Open Bilibili Comics source
2. Search Martial God Asura
3. Notice the genre "🔒 Paid" emoji "🔒" has a high surrogate "d83d"
4. Download any chapter

### Expected behavior

ComicInfo.xml to generate and Download to complete

### Actual behavior

ComicInfo.xml generation fails and there's a download error notification "In XML 1.0 the character 0xd83d is not valid"

### Crash logs

_No response_

### Tachiyomi version

Preview r5242

### Android version

N/A

### Device

N/A

### Other details

This is not exclusive to the genre field but applies to every other field. 

XmlUtil throws a error for having a high surrogate [here](https://github.com/pdvrieze/xmlutil/blob/672d85a61314957126502db639902b3a59648e6b/core/src/commonMain/kotlin/nl/adaptivity/xmlutil/core/KtXmlWriter.kt#L152)

CC @Shamicen 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Shamicen**
Fixes  #8537
I made a function to replace all Surrogates with the � character which should fix #8537. 

I expected XmlUtil to deal deal with illegal characters itself and it never came up in testing I'm sorry for the inconvenience.

### CODE REVIEW

**Comment by AntsyLich** [comment]
Tbn that when I tried with the jvm serializer it didn't throw any error with high surrogates. Maybe make issue upstream to get more info? And meanwhile disabling generation of ComicInfo.xml

**Comment by Shamicen** [comment]
> Tbn that when I tried with the jvm serializer it didn't throw any error with high surrogates. Maybe make issue upstream to get more info? 

I just opened an Issue upstream.
>And meanwhile disabling generation of ComicInfo.xml

We could disable it or merge this PR for now. Replacing the Surrogate pairs with different chars should work as a stop gap solution. 

I can understand not wanting code that will be removed again soon anyway though, especially if it isn't the ideal solution, so I will leave that decision to you guys.

**Comment by arkon** [comment]
Looking at the original issue, why is it even `0xd83d` (UTF-16)? Shouldn't it be UTF-8?

**Comment by Shamicen** [comment]
> Looking at the original issue, why is it even `0xd83d` (UTF-16)? Shouldn't it be UTF-8?
Isn't it because in Kotlin (and Java) Strings are encoded in UTF-16?

**Comment by arkon** [comment]
We'll wait for the dependency update.

**Pull request closed without merging**
