### PR TITLE
Hide LibraryToolbar pill if tab is visible

### PR DESCRIPTION
**Pull request by zbue**
Shown only if category tabs is not visible. `Show number of items` also falls under `Tabs` section, so it make sense....
With category tabs | Toolbar only
------------- | -------------
image | image

### CODE REVIEW

**Comment by AntsyLich** [comment]
How am i supposed to know the total count then

**Comment by zbue** [comment]
> How am i supposed to know the total count then

Maybe in stats screen (soonTM)? 😅

**Comment by AntsyLich** [comment]
👎 from me lol

**Comment by arkon** [comment]
No, this is intentional.

**Pull request closed without merging**
