### PR TITLE
Remove explicit clean task from gradle

### PR DESCRIPTION
**Pull request by jimman2003**
I checked gradle's task list, clean was still there
I also did a clean build for a sanity check

### CODE REVIEW

**Comment by arkon** [comment]
Is this just what the default clean task is? It's honestly just a leftover from the original project template.

**Comment by jimman2003** [comment]
I think so... At least it worked locally so..

**Comment by jimman2003** [comment]
maybe gradle 7 made it a default task?

**Comment by ghostbear** [comment]
I tried this and this makes it so the root build directory isn't removed

**Comment by jimman2003** [comment]
hmm..let me figure this out..

**Comment by jimman2003** [comment]
Yeah, I failed to notice the difference of the root build dir vs app/build.. 
turns out , that directory still remains :(

**Comment by jimman2003** [comment]
This PR is not needed,after all...

**Pull request closed without merging**
