### PR TITLE
steady chapter downloads feature

### PR DESCRIPTION
**Pull request by lmj0011**
closes https://github.com/inorichi/tachiyomi/issues/3295

### CODE REVIEW

**Comment by Sazaju** [comment]
What if we already downloaded like 5 chapters? Does it download the 6th? Or does it work only when the whole stack is consumed (only download the next one if not downloaded)?

**Comment by lmj0011** [comment]
> What if we already downloaded like 5 chapters? Does it download the 6th? Or does it work only when the whole stack is consumed (only download the next one if not downloaded)?

@Sazaju 
it just downloads the very next chapter, if it's not already downloaded. I do believe it would be more useful to have to next chapter that's not downloaded to download instead of _only_ the next chapter.

**Comment by Sazaju** [comment]
I think so too. Other issues have been closed as duplicates, including
those which mention this matter. So this PR only covers half of the problem
if it only considers the very next chapter. Could we hope to see more
commits coming on that?

**Comment by lmj0011** [comment]
@Sazaju yea, I plan to look into that soon, currently working on another project at the moment.

**Comment by Sazaju** [comment]
Thank you. {^_^}

**Comment by lmj0011** [comment]
@Sazaju 

> What if we already downloaded like 5 chapters? Does it download the 6th?


now it does: https://github.com/inorichi/tachiyomi/pull/3296/commits/0bcf54e53b0314f7c9ae77ed508287a65881fcc1

**Comment by Sazaju** [comment]
\\{^o^}/

**Comment by joseph619** [comment]
Just want to ask, does this affect page preloading in any way?

**Comment by lmj0011** [comment]
> Just want to ask, does this affect page preloading in any way? Like slowing it down or stopping it entirely.

I couldn't tell you for sure, since the chapters I read are always downloaded first.

@joseph619

**Comment by darshanio** [comment]
Will it add that next chapter to the top of the download queue?

**Comment by lmj0011** [comment]
@darshanio 

There's no priority set from what I remember, so I assume it would get added to the bottom of the queue.

As to anyone else that may be interested in using this feature, you can build your own apk off of [my fork](https://github.com/lmj0011/tachiyomi/tree/lmj0011-dev) as it doesn't appear this PR will be merged anytime in the near future.

Also note [my fork](https://github.com/lmj0011/tachiyomi/tree/lmj0011-dev) is currently [a bit behind the dev version](https://github.com/lmj0011/tachiyomi/compare/lmj0011-dev...inorichi:dev), so be sure to create a backup before proceeding.

**Comment by joseph619** [comment]
@lmj0011 Got this from Discord

_Download and chapter cache would need to be merged before it would work well_

You should preferably contact Syer10 on Discord as he has suggestions to make changes to this PR

**Comment by lmj0011** [comment]
@joseph619 

I'm not sure what that even means. I'll let you guys take it from here on any additions that this PR needs. I've been using this feature for the past few months and haven't had any problems.

**Comment by joseph619** [comment]
@jobobby04 can you give some input, sorry to tag

**Comment by jobobby04** [comment]
You probably have a fast network, but on slow networks it will stop you from going to the next chapter until the next one is fully downloaded.
Downloading chapters are saved in a tmp folder named like the actual chapter download, just with a _tmp at the end. Ideally it would use some kind of combination with the chapter cache, allowing the http page loader to load partial downloads. This could be achived by downloading pages to the chapter cache, and copying them to the download folder when done. 
Though this would require you to find some way to allow the cache to ignore the size limit it imposes, but I dont think it would be impossible

**Comment by lmj0011** [comment]
@jobobby04

The feature only works on an unmetered connection, however I understand it being a bad user experience for readers on slow Wi-Fi and whatnot.

The merging idea you explain sounds good in theory but I'm not looking to dip back into this code again so like I said in my last comment, I'll let another contributor handled the finishing touches. I myself am currently busy with a another project.

**Comment by soredake** [comment]
Any progress on this?

**Comment by lmj0011** [comment]
@soredake 

The feature works, it's just not up to the satisfaction of the core collaborators.

feel free to test it out, the apk with this feature can be downloaded here:
https://github.com/lmj0011/tachiyomi/releases/tag/0.11.1

**Comment by Sazaju** [comment]
Well, if the only criticism is that it may not show the best performances
on slow networks but nobody wants to dig deeper for now, being pragmatic I
would merge it and wait for someone to complain about it before to dig in
further. If no one is concerned by the issue or feel that it is good
enough, then blocking the change would not be justified, but we can't know
unless someone actually experiences it.

**Comment by lmj0011** [comment]
> Well, if the only criticism is that it may not show the best performances
> on slow networks but nobody wants to dig deeper for now, being pragmatic I
> would merge it and wait for someone to complain about it before to dig in
> further. If no one is concerned by the issue or feel that it is good
> enough, then blocking the change would not be justified, but we can't know
> unless someone actually experiences it.

@Sazaju 

Have you actually used it?
https://github.com/lmj0011/tachiyomi/releases/tag/v0.11.1

**Comment by Sazaju** [comment]
Is it in the app that can be updated from F-Droid? If not, then I don't
plan to use it.
I am used to open issues and to contribute for what I can, but I don't plan
to play a developer role in every app I open an issue on.
My time is scarce, and my low skills in Android make it low in my priority
stack.
So I don't want to build an APK myself, install a tachiyiomi variant,
taking care of not corrupting the one I have (backups and the like), just
to make some tests.

I am interested in the feature and if I see it in the app (even as
experimental) I will gladly use it and report if I face some issues.

**Comment by arkon** [comment]
Superseded by #7226

**Pull request closed without merging**
