### PR TITLE
Lessen the use of GlobalScope `launchIO`

### PR DESCRIPTION
**Pull request by AntsyLich**

### CODE REVIEW

**Comment by arkon** [comment]
A bunch of these jobs shouldn't actually be cancelled if their view/presenter scopes are cancelled.

**Comment by AntsyLich** [comment]
do i wrap them with `NonCancelable` context?

**Comment by arkon** [comment]
@ghostbear what should be preferred in this codebase?

**Comment by ivaniskandar** [comment]
Ideally file operations should be moved to a separate job but for now using NonCancellable context should work

**Pull request merged**
